version = 0.1
[default.deploy.parameters]
stack_name = "chapter06-stack"
resolve_s3 = true
s3_prefix = "chapter06-stack"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
